# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.1.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: inon@umich.edu
author_name: ino
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_puzzlemi
project_short_description: A JupyterLab extension.
python_name: jupyterlab_puzzlemi
repository: ''
test: true

